name: Release KDIS

on:
  push:
    tags: ['v*']  # Match tags like v2.11.0

permissions:
  contents: write  # For creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Debug event
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Tag: ${{ github.ref_name }}"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # For changelog access

    - name: Package source
      run: |
        # Create .tar.gz and .zip from source (excluding .git)
        tar --exclude='.git' -czf kdis-${{ github.ref_name }}.tar.gz .
        zip -r kdis-${{ github.ref_name }}.zip . -x ".git/*"

    - name: Extract changelog entry
      run: |
        # Extract changelog section for the tag (e.g., ## [v2.11.0])
        awk '/^## \[${{ github.ref_name }}\]/{flag=1; next} /^## \[/ {flag=0} flag' CHANGELOG.md > release-notes.md || echo "No changelog entry for ${{ github.ref_name }}" > release-notes.md

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          kdis-${{ github.ref_name }}.tar.gz
          kdis-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        body_path: release-notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
